services:
  baloniy_lorem_ipsum.baloniy_ipsum:
    class: Baloniy\LoremIpsumBundle\BaloniyIpsum
    public: true
    arguments:
      [ '@?', '@?', '@baloniy_lorem_ipsum.word_provider' ]

  baloniy_lorem_ipsum.baloniy_word_provider:
    class: Baloniy\LoremIpsumBundle\BaloniyWordProvider
    public: false

  Baloniy\LoremIpsumBundle\BaloniyIpsum:
    alias: 'baloniy_lorem_ipsum.baloniy_ipsum'
    public: false

  baloniy_lorem_ipsum.word_provider:
    alias: 'baloniy_lorem_ipsum.baloniy_word_provider'